name: CI

on:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read

jobs:
  indexer:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    env:
      ACCES_KEY_ID: ${{ secrets.ACCES_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      BUCKET: staking-eras
      REGION: ${{ secrets.REGION }}
    strategy:
      matrix:
        chain:
          - "dot"
          - "ksm"
          - "wnd"
          - "pas"
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1
      - name: Install deps
        run: bun install
      - name: Main
        run: CHAIN=${{ matrix.chain }} bun run src/main.ts

  build-status:
    runs-on: ubuntu-latest
    needs: [indexer]
    if: always()
    steps:
      - run: ${{!contains(needs.*.result, 'failure')}}
